inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false
